language: rust
matrix:
    fast_finish: true
    include:
        - rust: nightly
        - rust: beta
        - rust: stable

sudo: false

cache:
    apt: true
    directories:
        - $TRAVIS_BUILD_DIR/target
        - $HOME/.cargo
        
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup install nightly
  - which rustfmt || cargo +nightly install --force rustfmt-nightly

script:
  - cargo +nightly fmt -- --write-mode diff
  - cargo check
  - cargo test --verbose $FEATURES -- --nocapture
  # - cd external_markdown_tests
  # - cargo test --verbose $FEATURES -- --nocapture

addons:
  apt:
    packages:
      - libssl-dev
      
before_deploy:
  - cargo install mdbook
  - cd book
  - mdbook build
  - cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: book/book
  on:
    branch: master

notifications:
email: false
