[package]
name = "external_markdown_tests"
version = "0.1.0"
authors = ["Victor Polevoy <maintainer@thefx.co>"]
build = "build.rs"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"
toornament = { path = "../" }
